package postman

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/dataGriff/api-caller/internal/project"
)

func mustRead(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func has(t *testing.T, text string, wants ...string) {
	t.Helper()
	for _, w := range wants {
		if !strings.Contains(text, w) {
			t.Errorf("missing %q in:\n%s", w, text)
		}
	}
}

func TestImportCollection(t *testing.T) {
	out := t.TempDir()
	res, err := Import("testdata/collection.json", Options{OutDir: out, EnvFiles: []string{"testdata/staging.postman_environment.json"}})
	if err != nil {
		t.Fatal(err)
	}
	if res.Requests != 14 {
		t.Errorf("requests = %d, want 14", res.Requests)
	}
	names := map[string]bool{}
	for _, f := range res.Files {
		names[filepath.Base(f)] = true
	}
	for _, want := range []string{"auth.http", "todos.http", "todos-archive.http", "todo-api.http", "todo-api.tricky-body.body.txt", "http-client.env.json", "http-client.private.env.json", "apic.yaml"} {
		if !names[want] {
			t.Errorf("%s not written; files = %v", want, res.Files)
		}
	}
	if res.BaseURL != "https://api.example.com" || res.EnvFile == "" || res.PrivateEnvFile == "" {
		t.Errorf("result = %+v", res)
	}

	auth := mustRead(t, filepath.Join(out, "auth.http"))
	has(t, auth,
		"# auth — generated by `apic import` from \"collection.json\". Edit freely.\n",
		"\n### Log in\n# @name log-in\n# @description Exchange credentials for a token.\n# @auth none\n# @capture token = body.$.access_token\n# @assert status == 200\n# @assert body.$.access_token exists\n# @assert body.$.user.name == alice\n# @assert header.content-type contains json\nPOST {{baseUrl}}/auth/login\nContent-Type: application/json\n# X-Debug: 1  (disabled)\n\n{\"user\": \"{{user}}\", \"password\": \"{{password}}\"}\n",
		"\n### Who am I\n# @name who-am-i\n# @assert status == 200\n# @assert header.x-request-id exists\n# @assert duration < 500\nGET {{baseUrl}}/me\n",
	)
	if strings.Contains(auth, "# @auth bearer") {
		t.Error("the collection auth is the project default, not repeated per request")
	}

	todos := mustRead(t, filepath.Join(out, "todos.http"))
	has(t, todos,
		"@id = 42\n",
		"\n### List todos\n# @name list-todos\n# @assert body.$.items[0].id exists\nGET {{baseUrl}}/todos?done=true&limit={{pageSize}}\n    # &cursor=abc  (disabled)\nX-Api-Key: {{apiKey}}\n",
		"\n### Get todo\n# @name get-todo\nGET {{baseUrl}}/todos/{{id}}\nX-Api-Key: {{apiKey}}\n",
		"\n### Get todo\n# @name get-todo-2\nGET {{baseUrl}}/todos/{{$uuid}}\n",
	)

	archive := mustRead(t, filepath.Join(out, "todos-archive.http"))
	has(t, archive,
		"POST {{baseUrl}}/todos/{{id}}/attachments\nContent-Type: multipart/form-data; boundary=WebAppBoundary\nX-Api-Key: {{apiKey}}\n\n--WebAppBoundary\nContent-Disposition: form-data; name=\"title\"\n\nQuarterly\n--WebAppBoundary\nContent-Disposition: form-data; name=\"file\"; filename=\"report.pdf\"\nContent-Type: application/pdf\n\n< ./report.pdf\n--WebAppBoundary--\n",
		"POST {{baseUrl}}/todos/search\nContent-Type: application/x-www-form-urlencoded\nX-Api-Key: {{apiKey}}\n\nq=a+b%26c&owner={{user}}\n",
		"POST {{baseUrl}}/graphql\nContent-Type: application/json\nX-Api-Key: {{apiKey}}\n\n{\"query\":\"query Todos($done: Boolean) { todos(done: $done) { id } }\",\"variables\":{\"done\":true}}\n",
		"PUT {{baseUrl}}/todos/import\nX-Api-Key: {{apiKey}}\n\n< ./todos.csv\n",
	)

	root := mustRead(t, filepath.Join(out, "todo-api.http"))
	has(t, root,
		"# @auth aws region=eu-west-2 service=execute-api\n",
		"# @auth oauth2 tokenUrl={{tokenUrl}} clientId={{clientId}} clientSecret={{clientSecret}} scope=\"read write\" clientAuth=basic\n",
		"# @auth basic alice \"s3cret pass\"\n",
		"\n### Digest\n# @name digest\n# @auth digest alice {{password}}\nGET {{baseUrl}}/digest\n",
		"\n### Tricky ### body\n# @name tricky-body\nPOST {{baseUrl}}/notes\nContent-Type: text/plain\n\n< ./todo-api.tricky-body.body.txt\n",
	)
	if got := mustRead(t, filepath.Join(out, "todo-api.tricky-body.body.txt")); got != "### heading\nbody text" {
		t.Errorf("side file = %q", got)
	}

	var env map[string]map[string]string
	if err := json.Unmarshal([]byte(mustRead(t, res.EnvFile)), &env); err != nil {
		t.Fatal(err)
	}
	if env["$shared"]["baseUrl"] != "https://api.example.com" || env["$shared"]["pageSize"] != "20" || env["$shared"]["unused"] != "" {
		t.Errorf("shared = %v", env["$shared"])
	}
	if env["staging-eu"]["baseUrl"] != "https://staging.example.com" || env["staging-eu"]["user"] != "alice" || env["staging-eu"]["password"] != "" || env["staging-eu"]["old"] != "" {
		t.Errorf("staging = %v", env["staging-eu"])
	}
	var private map[string]map[string]string
	if err := json.Unmarshal([]byte(mustRead(t, res.PrivateEnvFile)), &private); err != nil {
		t.Fatal(err)
	}
	if private["staging-eu"]["password"] != "s3cret" || len(private) != 1 {
		t.Errorf("private = %v", private)
	}
	// File modes are not meaningful on Windows.
	if info, err := os.Stat(res.PrivateEnvFile); err != nil || (runtime.GOOS != "windows" && info.Mode().Perm() != 0o600) {
		t.Errorf("private env file mode: %v %v", info, err)
	}
	has(t, mustRead(t, filepath.Join(out, "apic.yaml")), "env: staging-eu\n", "auth:\n  default: \"bearer {{token}}\"\n")

	// What could not be carried over is reported, by request.
	got := map[string]string{}
	for _, u := range res.Unsupported {
		got[u.Request+"|"+u.What] = u.Reason
	}
	for _, key := range []string{
		"log-in|pm.expect(jsonData.roles).to.be.an('array');",
		"who-am-i|pre-request script",
		"upload-attachment|file part file",
		"raw-file-body|body file",
	} {
		if _, ok := got[key]; !ok {
			t.Errorf("unsupported %q not reported; got %v", key, got)
		}
	}
	if len(res.Unsupported) != 4 {
		t.Errorf("unsupported = %+v", res.Unsupported)
	}

	// The generated project parses and validates as written, part files
	// aside, which the notes point at.
	for _, f := range []string{"report.pdf", "todos.csv"} {
		if err := os.WriteFile(filepath.Join(out, f), []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	p, err := project.Load(out)
	if err != nil {
		t.Fatal(err)
	}
	for _, d := range p.Validate() {
		if d.Severity == "error" {
			t.Errorf("validate: %s", d)
		}
	}
	if len(p.Requests()) != 14 {
		t.Errorf("project has %d requests", len(p.Requests()))
	}

	// A second run keeps what exists.
	res2, err := Import("testdata/collection.json", Options{OutDir: out})
	if err != nil {
		t.Fatal(err)
	}
	if len(res2.Files) != 0 || len(res2.Skipped) < 6 || res2.Requests != 14 {
		t.Errorf("second run: files=%v skipped=%v requests=%d", res2.Files, res2.Skipped, res2.Requests)
	}
}

func TestImportRefusesV1AndNonCollections(t *testing.T) {
	dir := t.TempDir()
	v1 := filepath.Join(dir, "v1.json")
	_ = os.WriteFile(v1, []byte(`{"id": "x", "name": "old", "order": [], "requests": [], "info": {"schema": "https://schema.getpostman.com/json/collection/v1.0.0/"}}`), 0o644)
	if _, err := Import(v1, Options{OutDir: dir}); err == nil || !strings.Contains(err.Error(), "v1") {
		t.Errorf("v1: %v", err)
	}
	notOne := filepath.Join(dir, "openapi.json")
	_ = os.WriteFile(notOne, []byte(`{"openapi": "3.0.0", "paths": {}}`), 0o644)
	if _, err := Import(notOne, Options{OutDir: dir}); err == nil {
		t.Error("an OpenAPI document is not a collection")
	}
	if !LooksLikeCollection([]byte(`{"info": {"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"}, "item": []}`)) || LooksLikeCollection([]byte(`{"openapi": "3.1.0"}`)) {
		t.Error("collection detection")
	}
	if !LooksLikeEnvironment([]byte(`{"name": "x", "values": [], "_postman_variable_scope": "environment"}`)) || LooksLikeEnvironment([]byte(`{"item": []}`)) {
		t.Error("environment detection")
	}
	env := filepath.Join(dir, "env.json")
	_ = os.WriteFile(env, []byte(`{"nope": true}`), 0o644)
	col := filepath.Join(dir, "c.json")
	_ = os.WriteFile(col, []byte(`{"info": {"name": "c", "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"}, "item": [{"name": "ping", "request": "https://x/ping"}]}`), 0o644)
	if _, err := Import(col, Options{OutDir: dir, EnvFiles: []string{env}}); err == nil || !strings.Contains(err.Error(), "not a Postman environment") {
		t.Errorf("bad env file: %v", err)
	}
	res, err := Import(col, Options{OutDir: filepath.Join(dir, "out")})
	if err != nil || res.Requests != 1 {
		t.Fatalf("v2.0 with a string request: %v %+v", err, res)
	}
	has(t, mustRead(t, filepath.Join(dir, "out", "c.http")), "\n### ping\n# @name ping\nGET https://x/ping\n")
	if res.EnvFile != "" {
		t.Error("no variables, no env file")
	}
}

func TestTranslateTests(t *testing.T) {
	got := translateTests([]string{
		`pm.test("status", function () {`,
		`  pm.response.to.have.status(201);`,
		`  pm.response.to.have.status("Created");`,
		`  const body = pm.response.json();`,
		`  pm.expect(body.items[0]["k.y"]).to.equal(3);`,
		`  pm.expect(body.ok).to.be.true;`,
		`  pm.expect(body.name).to.include('ali');`,
		`  pm.expect(pm.response.text()).to.include("hello");`,
		`  pm.expect(pm.response.headers.get('Location')).to.eql("/todos/1");`,
		`  pm.collectionVariables.set("id", body.id);`,
		`  pm.globals.set("loc", pm.response.headers.get("Location"));`,
		`  pm.environment.set("tok", pm.response.json().token);`,
		`  pm.expect(other.x).to.eql(1);`,
		`  // a comment`,
		`});`,
	})
	wantAsserts := []string{"status == 201", "statusText == Created", `body.$.items[0]["k.y"] == 3`, "body.$.ok == true", "body.$.name contains ali", "body contains hello", "header.location == /todos/1"}
	if strings.Join(got.Asserts, "|") != strings.Join(wantAsserts, "|") {
		t.Errorf("asserts = %q", got.Asserts)
	}
	wantCaptures := []string{"id = body.$.id", "loc = header.location", "tok = body.$.token"}
	if strings.Join(got.Captures, "|") != strings.Join(wantCaptures, "|") {
		t.Errorf("captures = %q", got.Captures)
	}
	if len(got.Unsupported) != 1 || got.Unsupported[0] != "pm.expect(other.x).to.eql(1);" {
		t.Errorf("unsupported = %q", got.Unsupported)
	}
}

// A pm.test on one line reads the same as the block form: an arrow
// expression, an arrow block or a function block, each statement inside
// translated or reported on its own.
func TestTranslateOneLineTests(t *testing.T) {
	got := translateTests([]string{
		`pm.test("ok", () => pm.response.to.have.status(200));`,
		`pm.test('fast', function () { pm.expect(pm.response.responseTime).to.be.below(500); });`,
		"pm.test(`both`, () => { pm.response.to.have.header(\"ETag\"); pm.expect(pm.response.text()).to.include(\"x\") })",
		`pm.test("custom", () => pm.expect(tv4.validate(1, 2)).to.be.true);`,
	})
	want := []string{"status == 200", "duration < 500", "header.etag exists", "body contains x"}
	if strings.Join(got.Asserts, "|") != strings.Join(want, "|") {
		t.Errorf("asserts = %q", got.Asserts)
	}
	if len(got.Unsupported) != 1 || got.Unsupported[0] != "pm.expect(tv4.validate(1, 2)).to.be.true" {
		t.Errorf("unsupported = %q", got.Unsupported)
	}
}

func TestImportAPIKeyInQueryOpensTheQueryString(t *testing.T) {
	dir := t.TempDir()
	col := filepath.Join(dir, "c.json")
	_ = os.WriteFile(col, []byte(`{"info": {"name": "c", "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},
"auth": {"type": "apikey", "apikey": [{"key": "in", "value": "query"}, {"key": "key", "value": "api_key"}, {"key": "value", "value": "{{apiKey}}"}]},
"item": [{"name": "users", "request": "https://x/users"}, {"name": "search", "request": "https://x/search?q=1"},
{"name": "upload", "request": {"method": "POST", "url": "https://x/up", "body": {"mode": "formdata", "formdata": [{"key": "cv", "type": "file", "src": "résumé.pdf"}]}}}]}`), 0o644)
	if _, err := Import(col, Options{OutDir: filepath.Join(dir, "out")}); err != nil {
		t.Fatal(err)
	}
	got := mustRead(t, filepath.Join(dir, "out", "c.http"))
	has(t, got, "GET https://x/users\n    ?api_key={{apiKey}}\n", "GET https://x/search?q=1\n    &api_key={{apiKey}}\n",
		"Content-Disposition: form-data; name=\"cv\"; filename=\"résumé.pdf\"\n")
	p, err := project.Load(filepath.Join(dir, "out"))
	if err != nil {
		t.Fatal(err)
	}
	if u := p.Requests()[0].URL; u != "https://x/users?api_key={{apiKey}}" {
		t.Errorf("parsed url = %q", u)
	}
	m, err := p.Requests()[2].Multipart()
	if err != nil || m.Parts[0].Filename != "résumé.pdf" {
		t.Errorf("non-ASCII filename round trip: %+v %v", m, err)
	}
}
