package postman

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/dataGriff/api-caller/internal/httpfile"
)

// Options controls generation.
type Options struct {
	OutDir   string   // directory to write into
	EnvFiles []string // Postman environment exports, one environment each
	Force    bool     // overwrite existing files
}

// Result summarises what was generated. It has the shape of the OpenAPI
// importer's result plus what could not be translated.
type Result struct {
	Files          []string      `json:"files"`
	Requests       int           `json:"requests"`
	BaseURL        string        `json:"base_url,omitempty"`
	EnvFile        string        `json:"env_file,omitempty"`
	PrivateEnvFile string        `json:"private_env_file,omitempty"`
	Skipped        []string      `json:"skipped,omitempty"` // existing files kept (use --force)
	Unsupported    []Unsupported `json:"unsupported,omitempty"`
}

// Unsupported is one thing the collection had that the .http files cannot
// carry, with the request it belongs to and a one-line reason.
type Unsupported struct {
	Request string `json:"request"` // request id, or "collection"
	What    string `json:"what"`    // the script line, auth type or body mode
	Reason  string `json:"reason"`
}

// Import reads a Postman collection and writes .http files, an env file
// per Postman environment given, and apic.yaml when the collection has a
// default auth.
func Import(collectionPath string, opts Options) (*Result, error) {
	data, err := os.ReadFile(collectionPath) //nolint:gosec // the collection the user named on the command line
	if err != nil {
		return nil, err
	}
	c, err := parseCollection(data)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", collectionPath, err)
	}
	if opts.OutDir == "" {
		opts.OutDir = "."
	}
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil { //nolint:gosec // a scaffolded project directory the user browses and edits
		return nil, err
	}
	g := &generator{res: &Result{}, names: map[string]int{}, collectionAuth: c.Auth}

	// Requests grouped by the file they land in, in collection order.
	rootFile := kebab(c.Info.Name)
	g.walk(c.Item, nil, rootFile, c.Auth)

	// Collection-level auth becomes the project default.
	var defaultAuth string
	if c.Auth != nil && c.Auth.Type != "" && c.Auth.Type != "noauth" {
		line, headers, query, ok := g.authSpec(c.Auth, "collection")
		switch {
		case ok && line != "":
			defaultAuth = line
		case ok:
			// An API key on the collection applies to every request as a
			// header or a query value; those are written per request.
			for _, f := range g.order {
				for _, r := range g.files[f] {
					if r.inherits {
						r.Headers = append(r.Headers, headers...)
						r.Query = append(r.Query, query...)
					}
				}
			}
		}
	}

	for _, name := range g.order {
		file := filepath.Join(opts.OutDir, name+".http")
		if _, err := os.Stat(file); err == nil && !opts.Force {
			g.res.Skipped = append(g.res.Skipped, file)
			g.res.Requests += len(g.files[name])
			continue
		}
		var b strings.Builder
		fmt.Fprintf(&b, "# %s — generated by `apic import` from %q. Edit freely.\n", oneLine(nonEmpty(name, "requests")), oneLine(filepath.Base(collectionPath)))
		seenVars := map[string]bool{}
		for _, r := range g.files[name] {
			for _, v := range r.FileVars {
				if !seenVars[v.Name] {
					seenVars[v.Name] = true
					fmt.Fprintf(&b, "@%s = %s\n", v.Name, v.Value)
				}
			}
		}
		for _, r := range g.files[name] {
			if r.SideFile != "" {
				side := name + "." + r.Name + ".body" + r.SideExt
				sidePath := filepath.Join(opts.OutDir, side)
				r.BodyFile = "./" + side
				if _, err := os.Stat(sidePath); err == nil && !opts.Force {
					g.res.Skipped = append(g.res.Skipped, sidePath)
				} else {
					//nolint:gosec // a request body file the user edits and commits
					if err := os.WriteFile(sidePath, []byte(r.SideFile), 0o644); err != nil {
						return nil, err
					}
					g.res.Files = append(g.res.Files, sidePath)
				}
			}
			b.WriteString(r.render(defaultAuth != ""))
			g.res.Requests++
		}
		if err := os.WriteFile(file, []byte(b.String()), 0o644); err != nil { //nolint:gosec // a .http file the user edits and commits
			return nil, err
		}
		g.res.Files = append(g.res.Files, file)
	}

	// Variables: the collection's into $shared, each environment file into
	// an environment of its own; secrets into the private file.
	public := map[string]map[string]string{}
	private := map[string]map[string]string{}
	add := func(env string, vars []Variable) {
		for _, v := range vars {
			if !v.Active() || v.Key == "" {
				continue
			}
			target := public
			if v.Type == "secret" {
				target = private
			}
			if target[env] == nil {
				target[env] = map[string]string{}
			}
			target[env][v.Key] = string(v.Value)
		}
	}
	add("$shared", c.Variable)
	var envNames []string
	for _, envPath := range opts.EnvFiles {
		envData, err := os.ReadFile(envPath) //nolint:gosec // the environment file the user named
		if err != nil {
			return nil, err
		}
		var e Environment
		if err := json.Unmarshal(envData, &e); err != nil || e.Values == nil {
			return nil, fmt.Errorf("%s: not a Postman environment export", envPath)
		}
		envName := kebab(nonEmpty(e.Name, strings.TrimSuffix(filepath.Base(envPath), filepath.Ext(envPath))))
		envNames = append(envNames, envName)
		if public[envName] == nil {
			public[envName] = map[string]string{} // an environment exists even when every value is a secret
		}
		add(envName, e.Values)
	}
	if shared := public["$shared"]; shared != nil {
		for _, key := range []string{"baseUrl", "base_url", "baseURL", "url", "host"} {
			if v, ok := shared[key]; ok && g.res.BaseURL == "" {
				g.res.BaseURL = v
			}
		}
	}
	if len(public) > 0 {
		p, err := writeEnv(filepath.Join(opts.OutDir, "http-client.env.json"), public, 0o644, opts.Force, g.res)
		if err != nil {
			return nil, err
		}
		g.res.EnvFile = p
	}
	if len(private) > 0 {
		p, err := writeEnv(filepath.Join(opts.OutDir, "http-client.private.env.json"), private, 0o600, opts.Force, g.res)
		if err != nil {
			return nil, err
		}
		g.res.PrivateEnvFile = p
	}

	if defaultAuth != "" || len(envNames) > 0 {
		var y strings.Builder
		y.WriteString("# yaml-language-server: $schema=https://datagriff.github.io/api-caller/schemas/apic.schema.json\n")
		if len(envNames) > 0 {
			fmt.Fprintf(&y, "env: %s\n", envNames[0])
		}
		if defaultAuth != "" {
			fmt.Fprintf(&y, "auth:\n  default: %s\n", yamlString(defaultAuth))
		}
		cfg := filepath.Join(opts.OutDir, "apic.yaml")
		if _, err := os.Stat(cfg); err == nil && !opts.Force {
			g.res.Skipped = append(g.res.Skipped, cfg)
		} else {
			if err := os.WriteFile(cfg, []byte(y.String()), 0o644); err != nil { //nolint:gosec // project config the user edits and commits
				return nil, err
			}
			g.res.Files = append(g.res.Files, cfg)
		}
	}
	return g.res, nil
}

// parseCollection decodes a collection and refuses the v1 format.
func parseCollection(data []byte) (*Collection, error) {
	if !looksLikeCollection(data) {
		return nil, errors.New("not a Postman collection (no info.schema and no item list)")
	}
	var c Collection
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, err
	}
	schema := strings.ToLower(c.Info.Schema)
	switch {
	case strings.Contains(schema, "/v1.") || (schema == "" && c.Item == nil):
		return nil, errors.New("a Postman v1 collection is not supported: export it again as Collection v2.1")
	case schema != "" && !strings.Contains(schema, "/v2."):
		return nil, fmt.Errorf("unsupported collection schema %q: export it as Collection v2.1", c.Info.Schema)
	}
	return &c, nil
}

func writeEnv(p string, envs map[string]map[string]string, mode os.FileMode, force bool, res *Result) (string, error) {
	if _, err := os.Stat(p); err == nil && !force {
		res.Skipped = append(res.Skipped, p)
		return p, nil
	}
	data, err := json.MarshalIndent(envs, "", "  ")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(p, append(data, '\n'), mode); err != nil { //nolint:gosec // the env file's mode is the caller's choice: 0600 for secrets
		return "", err
	}
	res.Files = append(res.Files, p)
	return p, nil
}

// generator accumulates requests by file.
type generator struct {
	res            *Result
	files          map[string][]*request
	order          []string
	names          map[string]int
	collectionAuth *Auth // becomes auth.default; requests under it carry no # @auth of their own
}

// request is one generated request block.
type request struct {
	Name        string
	Title       string
	Description string
	Method      string
	URL         string
	Query       []string // commented continuation lines (disabled parameters)
	Headers     []string // header lines, comments included
	Auth        string   // `# @auth ...` value; "none" when the request opts out
	inherits    bool     // no auth of its own: the collection default applies
	ContentType string   // set when the body decides it and no header does
	Body        string
	BodyFile    string // `< file`
	SideFile    string // body text that must go into a side file
	SideExt     string
	FileVars    []fileVar
	Asserts     []string
	Captures    []string
}

type fileVar struct{ Name, Value string }

func (g *generator) walk(items []Item, folders []string, rootFile string, inherited *Auth) {
	for _, it := range items {
		auth := inherited
		if it.Auth != nil && it.Auth.Type != "" && it.Auth.Type != "inherit" {
			auth = it.Auth
		}
		if it.IsFolder() {
			g.walk(it.Item, append(append([]string(nil), folders...), it.Name), rootFile, auth)
			continue
		}
		file := rootFile
		if len(folders) > 0 {
			parts := make([]string, len(folders))
			for i, f := range folders {
				parts[i] = kebab(f)
			}
			file = strings.Join(parts, "-")
		}
		r := g.request(it, auth)
		if g.files == nil {
			g.files = map[string][]*request{}
		}
		if _, ok := g.files[file]; !ok {
			g.order = append(g.order, file)
		}
		g.files[file] = append(g.files[file], r)
	}
}

func (g *generator) note(req, what, reason string) {
	g.res.Unsupported = append(g.res.Unsupported, Unsupported{Request: req, What: what, Reason: reason})
}

var (
	rePathVar     = regexp.MustCompile(`(/|^):([A-Za-z_][\w-]*)`)
	reNonWord     = regexp.MustCompile(`[^A-Za-z0-9]+`)
	reDynamicVars = strings.NewReplacer("{{$guid}}", "{{$uuid}}", "{{$randomUUID}}", "{{$uuid}}")
)

func (g *generator) request(it Item, folderAuth *Auth) *request {
	req := it.Request
	name := uniqueName(kebab(it.Name), g.names)
	r := &request{Name: name, Title: oneLine(it.Name), Method: strings.ToUpper(nonEmpty(req.Method, "GET"))}
	if d := strings.TrimSpace(strings.SplitN(string(nonEmptyText(req.Description, it.Description)), "\n", 2)[0]); d != "" && d != r.Title {
		r.Description = oneLine(d)
	}

	// URL: Postman's {{var}} is apic's, :param becomes {{param}} with its
	// value as a file variable, disabled query parameters become comments.
	raw := strings.TrimSpace(req.URL.Raw)
	pathPart, query, hasQuery := strings.Cut(raw, "?")
	pathPart = rePathVar.ReplaceAllString(pathPart, "$1{{$2}}")
	raw = pathPart
	if hasQuery {
		raw += "?" + query
	}
	r.URL = reDynamicVars.Replace(oneLine(raw))
	for _, v := range req.URL.Variable {
		if v.Key != "" && string(v.Value) != "" {
			r.FileVars = append(r.FileVars, fileVar{Name: v.Key, Value: oneLine(string(v.Value))})
		}
	}
	for _, q := range req.URL.Query {
		if q.Disabled {
			r.Query = append(r.Query, fmt.Sprintf("# &%s=%s  (disabled)", oneLine(q.Key), oneLine(q.Value)))
		}
	}

	hasContentType := false
	for _, h := range req.Header {
		key := oneLine(h.Key)
		if key == "" {
			continue
		}
		if h.Disabled {
			r.Headers = append(r.Headers, fmt.Sprintf("# %s: %s  (disabled)", key, oneLine(h.Value)))
			continue
		}
		if strings.EqualFold(key, "Content-Type") {
			hasContentType = true
		}
		r.Headers = append(r.Headers, key+": "+oneLine(h.Value))
	}

	// Auth: the request's own, else the folder's, else the collection's,
	// which the project default covers; any of them may be "noauth".
	auth := req.Auth
	if auth == nil || auth.Type == "" || auth.Type == "inherit" {
		auth = folderAuth
	}
	switch {
	case auth == nil || auth.Type == "" || auth.Type == "inherit":
	case auth == g.collectionAuth:
		r.inherits = true
	case auth.Type == "noauth":
		r.Auth = "none"
	default:
		if line, headers, query, ok := g.authSpec(auth, name); ok {
			r.Auth = line
			r.Headers = append(r.Headers, headers...)
			r.Query = append(r.Query, query...)
		}
	}

	if req.Body != nil && !req.Body.Disabled {
		g.body(r, req.Body, hasContentType)
	}
	if strings.EqualFold(r.ContentType, "multipart/form-data") || strings.HasPrefix(r.ContentType, "multipart/form-data;") {
		// The boundary in the body must be the one the header names.
		r.Headers = withoutContentType(r.Headers)
	}

	for _, ev := range it.Event {
		switch ev.Listen {
		case "test":
			t := translateTests(ev.Script.Exec)
			r.Asserts = append(r.Asserts, t.Asserts...)
			r.Captures = append(r.Captures, t.Captures...)
			for _, line := range t.Unsupported {
				g.note(name, oneLine(line), "test script line not translated; apic has no scripting")
			}
		case "prerequest":
			if len(strings.TrimSpace(strings.Join(ev.Script.Exec, ""))) > 0 {
				g.note(name, "pre-request script", "not translated; compute values with --var or a # @ref request instead")
			}
		}
	}
	return r
}

// body maps a Postman body onto the request.
func (g *generator) body(r *request, b *Body, hasContentType bool) {
	switch b.Mode {
	case "raw":
		text := strings.TrimRight(reDynamicVars.Replace(b.Raw), "\n")
		if text == "" {
			return
		}
		if !hasContentType && b.Options != nil {
			switch b.Options.Raw.Language {
			case "json":
				r.ContentType = "application/json"
			case "xml":
				r.ContentType = "application/xml"
			case "html":
				r.ContentType = "text/html"
			case "javascript":
				r.ContentType = "application/javascript"
			case "text":
				r.ContentType = "text/plain"
			}
		}
		if splitsBlock(text) {
			r.SideFile, r.SideExt = text, ".txt"
			if r.ContentType == "application/json" {
				r.SideExt = ".json"
			}
			return
		}
		r.Body = text
	case "urlencoded":
		var pairs []string
		for _, f := range b.Urlencoded {
			if f.Disabled || f.Key == "" {
				continue
			}
			pairs = append(pairs, formEscape(f.Key)+"="+formEscape(reDynamicVars.Replace(f.Value)))
		}
		if !hasContentType {
			r.ContentType = "application/x-www-form-urlencoded"
		}
		r.Body = strings.Join(pairs, "&")
	case "formdata":
		var parts strings.Builder
		for _, f := range b.Formdata {
			if f.Disabled || f.Key == "" {
				continue
			}
			parts.WriteString("--WebAppBoundary\n")
			if f.Type == "file" {
				src := strings.TrimSpace(string(f.Src))
				base := nonEmpty(baseName(src), f.Key)
				fmt.Fprintf(&parts, "Content-Disposition: form-data; name=%s; filename=%s\n", httpfile.QuoteParam(oneLine(f.Key)), httpfile.QuoteParam(oneLine(base)))
				if f.ContentType != "" {
					fmt.Fprintf(&parts, "Content-Type: %s\n", oneLine(f.ContentType))
				}
				fmt.Fprintf(&parts, "\n< ./%s\n", oneLine(base))
				if src != base {
					g.note(r.Name, "file part "+oneLine(f.Key), fmt.Sprintf("Postman pointed at %s; put %s next to the .http file", oneLine(src), oneLine(base)))
				}
				continue
			}
			fmt.Fprintf(&parts, "Content-Disposition: form-data; name=%s\n", httpfile.QuoteParam(oneLine(f.Key)))
			if f.ContentType != "" {
				fmt.Fprintf(&parts, "Content-Type: %s\n", oneLine(f.ContentType))
			}
			fmt.Fprintf(&parts, "\n%s\n", oneLine(reDynamicVars.Replace(f.Value)))
		}
		if parts.Len() == 0 {
			return
		}
		parts.WriteString("--WebAppBoundary--")
		r.ContentType = "multipart/form-data; boundary=WebAppBoundary"
		r.Body = parts.String()
	case "file":
		if b.File == nil || b.File.Src == "" {
			return
		}
		base := baseName(b.File.Src)
		r.BodyFile = "./" + oneLine(base)
		if b.File.Src != base {
			g.note(r.Name, "body file", fmt.Sprintf("Postman pointed at %s; put %s next to the .http file", oneLine(b.File.Src), oneLine(base)))
		}
	case "graphql":
		if b.Graphql == nil {
			return
		}
		var vars json.RawMessage
		if v := strings.TrimSpace(b.Graphql.Variables); v != "" && json.Valid([]byte(v)) {
			vars = json.RawMessage(v)
		}
		payload := struct {
			Query     string          `json:"query"`
			Variables json.RawMessage `json:"variables,omitempty"`
		}{reDynamicVars.Replace(b.Graphql.Query), vars}
		data, _ := json.Marshal(payload)
		if !hasContentType {
			r.ContentType = "application/json"
		}
		r.Body = string(data)
	case "":
	default:
		g.note(r.Name, "body mode "+b.Mode, "not translated")
	}
}

// authSpec maps a Postman auth block onto a `# @auth` value, or onto
// header and query lines for an API key. ok is false when apic has no
// equivalent, which is then reported.
func (g *generator) authSpec(a *Auth, req string) (line string, headers, query []string, ok bool) {
	switch a.Type {
	case "bearer":
		return "bearer " + authArg(nonEmpty(param(a.Bearer, "token"), "{{token}}")), nil, nil, true
	case "basic":
		return "basic " + authArg(nonEmpty(param(a.Basic, "username"), "{{user}}")) + " " + authArg(nonEmpty(param(a.Basic, "password"), "{{password}}")), nil, nil, true
	case "digest":
		return "digest " + authArg(nonEmpty(param(a.Digest, "username"), "{{user}}")) + " " + authArg(nonEmpty(param(a.Digest, "password"), "{{password}}")), nil, nil, true
	case "apikey":
		key, value := oneLine(nonEmpty(param(a.Apikey, "key"), "X-Api-Key")), oneLine(nonEmpty(param(a.Apikey, "value"), "{{apiKey}}"))
		if param(a.Apikey, "in") == "query" {
			return "", nil, []string{"&" + key + "=" + value}, true
		}
		return "", []string{key + ": " + value}, nil, true
	case "awsv4":
		s := "aws"
		if v := param(a.Awsv4, "region"); v != "" {
			s += " region=" + authArg(v)
		}
		if v := param(a.Awsv4, "service"); v != "" {
			s += " service=" + authArg(v)
		}
		return s, nil, nil, true
	case "oauth2":
		grant := param(a.Oauth2, "grant_type")
		tokenURL := nonEmpty(param(a.Oauth2, "accessTokenUrl"), "{{tokenUrl}}")
		s := "oauth2 tokenUrl=" + authArg(tokenURL) + " clientId=" + authArg(nonEmpty(param(a.Oauth2, "clientId"), "{{clientId}}"))
		if v := param(a.Oauth2, "clientSecret"); v != "" {
			s += " clientSecret=" + authArg(v)
		}
		if v := param(a.Oauth2, "scope"); v != "" {
			s += " scope=" + authArg(v)
		}
		switch grant {
		case "", "client_credentials":
		case "password_credentials":
			s += " grant=password username=" + authArg(nonEmpty(param(a.Oauth2, "username"), "{{user}}")) + " password=" + authArg(nonEmpty(param(a.Oauth2, "password"), "{{password}}"))
		default:
			g.note(req, "oauth2 grant "+grant, "only client credentials and password grants map onto # @auth oauth2; browser flows need a token from elsewhere")
			return "", nil, nil, false
		}
		if param(a.Oauth2, "client_authentication") == "header" {
			s += " clientAuth=basic"
		}
		return s, nil, nil, true
	case "noauth", "inherit", "":
		return "", nil, nil, false
	}
	g.note(req, "auth "+a.Type, "apic has no equivalent; write the header yourself or use # @auth exec")
	return "", nil, nil, false
}

// authArg quotes a `# @auth` argument when it holds spaces.
func authArg(s string) string {
	s = oneLine(s)
	if strings.ContainsAny(s, " \t\"") {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}

func (r *request) render(hasDefaultAuth bool) string {
	var b strings.Builder
	title := r.Title
	if title == "" {
		title = r.Method + " " + r.URL
	}
	fmt.Fprintf(&b, "\n### %s\n", title)
	fmt.Fprintf(&b, "# @name %s\n", r.Name)
	if r.Description != "" {
		fmt.Fprintf(&b, "# @description %s\n", r.Description)
	}
	switch {
	case r.Auth == "none" && hasDefaultAuth:
		b.WriteString("# @auth none\n")
	case r.Auth != "" && r.Auth != "none":
		fmt.Fprintf(&b, "# @auth %s\n", r.Auth)
	}
	for _, c := range r.Captures {
		fmt.Fprintf(&b, "# @capture %s\n", c)
	}
	for _, a := range r.Asserts {
		fmt.Fprintf(&b, "# @assert %s\n", a)
	}
	fmt.Fprintf(&b, "%s %s\n", r.Method, r.URL)
	hasQuery := strings.Contains(r.URL, "?")
	for _, q := range r.Query {
		if !strings.HasPrefix(q, "#") && !hasQuery {
			// The parser appends continuation lines verbatim, so the first
			// active parameter opens the query string.
			q, hasQuery = "?"+strings.TrimPrefix(q, "&"), true
		}
		fmt.Fprintf(&b, "    %s\n", q)
	}
	if r.ContentType != "" {
		fmt.Fprintf(&b, "Content-Type: %s\n", r.ContentType)
	}
	for _, h := range r.Headers {
		b.WriteString(h + "\n")
	}
	switch {
	case r.BodyFile != "":
		b.WriteString("\n< " + r.BodyFile + "\n")
	case r.Body != "":
		b.WriteString("\n" + r.Body + "\n")
	}
	return b.String()
}

// baseName is the file name of a path Postman recorded on any OS: exports
// carry the author's machine's paths, Windows ones included.
func baseName(p string) string {
	return path.Base(strings.ReplaceAll(p, "\\", "/"))
}

func withoutContentType(headers []string) []string {
	out := headers[:0:0]
	for _, h := range headers {
		if strings.HasPrefix(strings.ToLower(h), "content-type:") {
			continue
		}
		out = append(out, h)
	}
	return out
}

// splitsBlock reports whether an inline body would be misread by the .http
// parser: a line starting with ### opens a new block and a body starting
// with `< ` refers to a file.
func splitsBlock(body string) bool {
	if t := strings.TrimSpace(body); strings.HasPrefix(t, "< ") || strings.HasPrefix(t, "<@ ") {
		return true
	}
	for _, line := range strings.Split(body, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "###") {
			return true
		}
	}
	return false
}

// formEscape percent-encodes a form field, leaving {{placeholders}} for the
// runner to fill in.
func formEscape(s string) string {
	out := url.QueryEscape(s)
	return strings.NewReplacer("%7B%7B", "{{", "%7D%7D", "}}").Replace(out)
}

func yamlString(s string) string {
	b, _ := json.Marshal(s) // a JSON string is a valid YAML double-quoted scalar
	return string(b)
}

func kebab(s string) string {
	s = reNonWord.ReplaceAllString(s, "-")
	s = strings.Trim(strings.ToLower(s), "-")
	if s == "" {
		return "request"
	}
	return s
}

func uniqueName(name string, seen map[string]int) string {
	seen[name]++
	if seen[name] == 1 {
		return name
	}
	return fmt.Sprintf("%s-%d", name, seen[name])
}

// oneLine collapses text into a single line, so a value from the
// collection cannot inject request blocks or directives into the file.
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func nonEmpty(s, fallback string) string {
	if strings.TrimSpace(s) == "" {
		return fallback
	}
	return s
}

func nonEmptyText(a, b flexText) flexText {
	if strings.TrimSpace(string(a)) == "" {
		return b
	}
	return a
}
