// Command errdocs writes docs/errors.md from runner.Catalogue and
// httpfile.Codes, so an error's code, exit status, hint and documentation
// live in one table in the code and cannot drift from the page. Run it with
// `task docs:errors`; TestErrorsPageIsCurrent fails when the page is stale.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dataGriff/api-caller/internal/httpfile"
	"github.com/dataGriff/api-caller/internal/runner"
)

func main() {
	out := flag.String("o", filepath.Join("docs", "errors.md"), "the page to write")
	check := flag.Bool("check", false, "fail if the page is stale instead of writing it")
	flag.Parse()
	page := Markdown()
	if *check {
		current, err := os.ReadFile(*out)
		if err != nil {
			log.Fatal(err)
		}
		if strings.ReplaceAll(string(current), "\r\n", "\n") != page {
			log.Fatalf("%s is stale; run `task docs:errors`", *out)
		}
		return
	}
	if err := os.WriteFile(*out, []byte(page), 0o644); err != nil { //nolint:gosec // a docs page in the repository, meant to be world-readable
		log.Fatal(err)
	}
}

const intro = `# Errors

<!-- Generated by scripts/errdocs from internal/runner/errors.go; edit the
catalogue there and run task docs:errors. -->

Every error apic reports carries a stable code. A script or an agent can
branch on the code rather than on the wording of the message, which may
improve from release to release; a code never changes meaning, and new ones
are only added.

The first digit groups them: **E1xx** is the request as written, **E2xx**
the command and the project around it, **E3xx** the network. The exit
status follows from the code: 2 for E1xx and E2xx, 3 for E3xx (see
[exit codes](cli.md#exit-codes)). A failed assertion is not an error: it
exits 1 and is reported in the result.

## Where the code appears

On a terminal, under the message:

` + "```text" + `
error: auth.http:9: missing variable
  {{token}}: it is captured by request "login"; run ` + "`apic run login`" + ` first, or pass --var token=...
  E101 missing variable · see https://datagriff.github.io/api-caller/errors/#e101
` + "```" + `

With ` + "`--json`" + `, as one object on **stderr** (stdout keeps only results, so a
pipe into ` + "`jq`" + ` is not disturbed):

` + "```json" + `
{"error":{"code":"E101","title":"missing variable","message":"auth.http:9: missing variable\n  {{token}}: it is captured by request …","hint":"Pass it with --var name=value, …","exit":2,"url":"https://datagriff.github.io/api-caller/errors/#e101"}}
` + "```" + `

Over [MCP](agents.md), a failed tool call carries the same object as its
structured content, and its text ends with the code, title and hint.

`

// Markdown is the whole page.
func Markdown() string {
	var b strings.Builder
	b.WriteString(intro)
	b.WriteString("## Summary\n\n| Code | Exit | Title |\n|---|---|---|\n")
	for _, e := range runner.Catalogue {
		fmt.Fprintf(&b, "| [%s](#%s) | %d | %s |\n", e.Code, anchor(e.Code), e.Exit, e.Title)
	}
	group := ""
	for _, e := range runner.Catalogue {
		if g := groupOf(e.Code); g != group {
			group = g
			fmt.Fprintf(&b, "\n## %s\n", g)
		}
		fmt.Fprintf(&b, "\n<a id=\"%s\"></a>\n\n### %s %s\n\n", anchor(e.Code), e.Code, e.Title)
		fmt.Fprintf(&b, "Exit %d. %s\n\n**What to do:** %s\n", e.Exit, e.About, e.Hint)
	}
	b.WriteString(`
## Validate diagnostics

` + "`apic validate`" + ` reports problems in the files before anything runs, each
with a line, a column and one of these codes (the ` + "`code`" + ` key of
` + "`validate --json`" + `). They are a separate namespace from the E codes above:
a file with an error-severity diagnostic refuses to run with
[E103](#e103).

| Code | Meaning |
|---|---|
`)
	names := make([]string, 0, len(httpfile.Codes))
	for name := range httpfile.Codes {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "| `%s` | %s |\n", name, escapeCell(httpfile.Codes[name]))
	}
	return b.String()
}

func anchor(c runner.Code) string { return strings.ToLower(string(c)) }

func groupOf(c runner.Code) string {
	switch string(c)[1] {
	case '1':
		return "E1xx: the request"
	case '2':
		return "E2xx: the command and project"
	default:
		return "E3xx: the network"
	}
}

// escapeCell keeps a table cell in one cell: a pipe outside backticks would
// start a new one.
func escapeCell(s string) string {
	var b strings.Builder
	code := false
	for _, r := range s {
		switch {
		case r == '`':
			code = !code
		case r == '|' && !code:
			b.WriteString(`\`)
		}
		b.WriteRune(r)
	}
	return b.String()
}
