// Package skills carries the Agent Skill that `apic skill` prints and
// installs: skills/apic in this repository, compiled into the binary so a
// project gets it from `apic init` or `apic skill install` without the
// repository or a network. SKILL.md is hand-written; references/ is
// generated by `task skill` and a test in scripts/skilldocs keeps it
// current.
package skills

import (
	"embed"
	"io/fs"
	"sort"
)

//go:embed apic/SKILL.md apic/references
var files embed.FS

// Name is the skill's directory name, in every location it is installed.
const Name = "apic"

// Files returns the skill's files by path relative to its directory,
// SKILL.md first and the rest sorted.
func Files() map[string]string {
	out := map[string]string{}
	_ = fs.WalkDir(files, Name, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		data, err := fs.ReadFile(files, path)
		if err != nil {
			return err
		}
		out[path[len(Name)+1:]] = string(data)
		return nil
	})
	return out
}

// Paths lists the skill's file paths, SKILL.md first.
func Paths() []string {
	var paths []string
	for p := range Files() {
		if p != "SKILL.md" {
			paths = append(paths, p)
		}
	}
	sort.Strings(paths)
	return append([]string{"SKILL.md"}, paths...)
}
